apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: cert-manager
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: cert-manager
spec:
  secretName: k8s-labels-validation-webhook-certs
  dnsNames:
    - k8s-labels-validation-webhook.cert-manager.svc
    - k8s-labels-validation-webhook.cert-manager.svc.cluster.local
  issuerRef:
    name: selfsigned-issuer