---
apiVersion: v1
kind: Service
metadata:
  name: k8s-labels-validation-webhook
  namespace: kube-system
  labels:
    app: k8s-labels-validation-webhook
spec:
  ports:
    - port: 8443
      targetPort: 8443
  selector:
    app: k8s-labels-validation-webhook
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: k8s-labels-validation-webhook
  namespace: kube-system
  annotations:
    cert-manager.io/inject-ca-from: cert-manager/selfsigned-cert
webhooks:
  - clientConfig:
      caBundle: Cg==
      service:
        name: k8s-labels-validation-webhook
        path: /mutate
        port: 8443
        namespace: kube-system
    sideEffects: None
    admissionReviewVersions: ["v1beta1"]
    failurePolicy: Fail
    name: mpod.kb.io
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
